sudo: false

language: python

python:
  - 2.7

install:
  - pip install -r requirements.txt

script:
  - export PYTHONPATH=$pwd
  - nosetests --with-coverage --cover-inclusive --tests ./tests/

after_success:
  - codecov
