sudo: false

language: python

python:
  - 2.7

install:
  - pip install codecov
  - pip install nose
script:
  - export PYTHONPATH=$pwd
  - nosetests --with-coverage --cover-inclusive

after_success:
  - codecov
